project_id = "dlaudfrhokdjtcmnhhap"

[functions.stripe-payment]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.create-payment]
enabled = true
verify_jwt = true

[functions.handle-webhook]
enabled = true
verify_jwt = false
