project_id = "dlaudfrhokdjtcmnhhap"

[functions.stripe-payment]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.create-payment]
enabled = true
verify_jwt = true
import_map = "./functions/create-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-payment/*.html" ]

[functions.handle-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/handle-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle-webhook/*.html" ]
